### ISSUE TITLE
Bug in Fee edition form

### ISSUE THREAD

**Issue by robgc** [bjjr/d12#1]
El campo valor admite valores como "-0.0001" que no son válidos.

**Comment by robgc** [comment]
Las anotación "Min" no funciona de forma correcta, esto se debe controlar mediante un Assert en el servicio correspondiente.

**Comment by javiparra17** [comment]
También puede ponerse un valor máximo de Fee en los requisitos, y controlarlo con la anotación @Range(min=0, max=X)

**Comment by robgc** [comment]
La anotación Range tampoco lo controla, se ha de controlar mediante servicios.

**Comment by javsanpar** [comment]
Solved with @DecimalMin
